services:
  web:
    image: ${REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG:-latest}
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=${CONTAINER_PORT:-3000}
    ports:
      - "${HOST_PORT:-80}:${CONTAINER_PORT:-3000}"
