pipeline {
  agent any

  environment {
    AWS_DEFAULT_REGION = credentials('AWS_DEFAULT_REGION') // opcional via credenciais
    ECR_REPOSITORY     = credentials('ECR_REPOSITORY')     // ou defina fixo aqui
    REGISTRY           = credentials('ECR_REGISTRY')       // ex.: 123456789012.dkr.ecr.us-east-1.amazonaws.com
    IMAGE_TAG          = 'latest'
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Login ECR') {
      steps {
        sh '''
        aws ecr get-login-password --region "${AWS_DEFAULT_REGION}" |         docker login --username AWS --password-stdin "${REGISTRY}"
        '''
      }
    }

    stage('Deploy (docker compose)') {
      steps {
        sh '''
        export REGISTRY="${REGISTRY}"
        export ECR_REPOSITORY="${ECR_REPOSITORY}"
        export IMAGE_TAG="${IMAGE_TAG}"
        export HOST_PORT="${HOST_PORT:-80}"
        export CONTAINER_PORT="${CONTAINER_PORT:-3000}"

        docker compose pull
        docker compose up -d
        docker ps
        '''
      }
    }
  }
}
